### ISSUE TITLE
同求一下说明文档....想知道此密钥协商的细节...求求求

### ISSUE THREAD

**Issue by cat-dumpling** [Kur0x/GroupCommu#8]

**Comment by Kur0x** [comment]
其实是毕业论文，晚上我整理一下发上来

**Comment by cat-dumpling** [comment]
好的，好的，真的是太感谢了，麻烦您了！
github上关于群密钥协商方面的真是太少了（也可能是我搜索的技巧不对）......


 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "KuroX"<notifications@github.com&gt;; 
发送时间: 2020年3月18日(星期三) 上午10:48
收件人: "Kur0x/GroupCommu"<GroupCommu@noreply.github.com&gt;; 
抄送: "cat-dumpling"<502846870@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Kur0x/GroupCommu] 同求一下说明文档....想知道此密钥协商的细节...求求求 (#8)





 
其实是毕业论文，晚上我整理一下发上来

**Comment by Kur0x** [comment]
@cat-dumpling 已更新说明文档

**Comment by cat-dumpling** [comment]
谢谢！谢谢！正在仔细研读！
